### ISSUE TITLE
"object has no attribute 'settings'" when using "Automatically power off x minute/s after idle state"

### ISSUE THREAD

**Issue by gretel** [Salandora/OctoPrint-AutomaticOnOffPlugin#1]
great plugin, thanks!
while it seems to work fine the log has plenty of this error:
```
2017-01-18 22:57:17,291 - octoprint.util.comm - ERROR - Error while processing hook automaticonoff for phase sent and command M105:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.1rc1-py2.7.egg/octoprint/util/comm.py", line 2113, in _process_command_phase
    hook_result = hook(self, phase, command, command_type, gcode)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_automaticonoff/__init__.py", line 235, in on_sent
    ignore_commands = [x.strip() for x in self.settings.get(["idle", "ignore_commands"]).split(',')]
AttributeError: 'AutomaticOnOffPlugin' object has no attribute 'settings'
```

**Comment by Salandora** [comment]
That one was already fixed in the devel branch, I have merged it to master now, please reinstall the plugin.
